parameters:

services:
    app.form.registration:
        class: AppBundle\Form\RegistrationType
        tags:
            - { name: form.type, alias: app_user_registration }

    app.avatar_uploader:
        class: AppBundle\FileUploader
        arguments: ['%avatar_directory%']

    app.lot_image_uploader:
        class: AppBundle\FileUploader
        arguments: ['%lot_image_directory%']

    app.doctrine_avatar_listener:
        class: AppBundle\EventListener\AvatarUploadSubscriber
        arguments: ['@app.avatar_uploader']
        tags:
            - { name: doctrine.event_subscriber}

    app.doctrine_lot_image_listener:
        class: AppBundle\EventListener\LotImageUploadSubscriber
        arguments: ['@app.lot_image_uploader']
        tags:
            - { name: doctrine.event_subscriber}

    app.registration:
        class: AppBundle\EventListener\RegistrationListener
        arguments: ['@router']
        tags:
            - { name: kernel.event_subscriber }

    acme_app.template.my_template:
        class: AppBundle\Template\MyCustomTemplate

    pagerfanta.view.my_template:
        class: Pagerfanta\View\DefaultView
        public: false
        arguments:
            - "@acme_app.template.my_template"
        tags: [{ name: pagerfanta.view, alias: my_template }]

    app.menu_builder:
        class: AppBundle\Menu\MenuBuilder
        arguments: ["@knp_menu.factory", "@doctrine.orm.entity_manager"]
        tags:
            - { name: knp_menu.menu_builder, method: createCatalogMenu, alias: category}