parameters:

services:
    app.form.registration:
        class: AppBundle\Form\RegistrationType
        tags:
            - { name: form.type, alias: app_user_registration }

    app.avatar_uploader:
        class: AppBundle\FileUploader
        arguments: ['%avatar_directory%']


    app.doctrine_avatar_listener:
        class: AppBundle\EventListener\AvatarUploadSubscriber
        arguments: ['@app.avatar_uploader']
        tags:
            - { name: doctrine.event_subscriber}

    app.registration:
        class: AppBundle\EventListener\RegistrationListener
        arguments: ['@router']
        tags:
            - { name: kernel.event_subscriber }